name: Build library and run tests
on:
  push:
    branches: [ master, devel ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    container: 
      image: bausma/mbed-dev-env:latest
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build STM NUCLEO-G491RB Example
        run: |
          cd stm_nucleo_g431rb
          make
#      - uses: actions/checkout@v3
#      - name: Build STM NUCLEO_G491RB Example
#        run: |
#          echo $(pwd)
#          ls
#          cd stm_nucleo_g431rb
#          make
